---
title: Manoj Rao
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  sections:
    title: Sections
    output: false
  uploads:
    title: Uploads
    output: true
subtitle: Analyst - Engineer - Researcher
description: This is the demo site for a Jekyll theme version of HTML5 UP's sleek,
  responsive site template Prologue.
author: Manoj Rao
email: rao.manoj@outlook.in
avatar: assets/images/Manoj-Rao_Headshot.png
baseurl: "/"
url: https://rao-manoj.github.io/manoj-rao-jekyll-project-2
twitter_url: 
facebook_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://linkedin.com/in/rao-manoj
github_url: 
stackoverflow_url: 
pinterest_url: 
slack_url: 
dribbble_url: 
google_analytics: UA-134532260-1
remote_theme: chrisbobbe/jekyll-theme-prologue
